void GuiEnable(void)
void GuiDisable(void)
void GuiLock(void)
void GuiUnlock(void)
bool GuiIsLocked(void)
void GuiSetAlpha(float alpha)
void GuiSetState(int state)
int GuiGetState(void)
void GuiSetFont(Font font)
Font GuiGetFont(void)
void GuiSetStyle(int control, int property, int value)
int GuiGetStyle(int control, int property)
void GuiLoadStyle(const char *fileName)
void GuiLoadStyleDefault(void)
void GuiEnableTooltip(void)
void GuiDisableTooltip(void)
void GuiSetTooltip(const char *tooltip)
const char *GuiIconText(int iconId, const char *text)
void GuiSetIconScale(int scale)
unsigned int *GuiGetIcons(void)
char **GuiLoadIcons(const char *fileName, bool loadIconsName)
void GuiDrawIcon(int iconId, int posX, int posY, int pixelSize, Color color)
int GuiWindowBox(Rectangle bounds, const char *title)
int GuiGroupBox(Rectangle bounds, const char *text)
int GuiLine(Rectangle bounds, const char *text)
int GuiPanel(Rectangle bounds, const char *text)
int GuiTabBar(Rectangle bounds, const char **text, int count, int *active)
int GuiScrollPanel(Rectangle bounds, const char *text, Rectangle content, Vector2 *scroll, Rectangle *view)
int GuiLabel(Rectangle bounds, const char *text)
int GuiButton(Rectangle bounds, const char *text)
int GuiLabelButton(Rectangle bounds, const char *text)
int GuiToggle(Rectangle bounds, const char *text, bool *active)
int GuiToggleGroup(Rectangle bounds, const char *text, int *active)
int GuiToggleSlider(Rectangle bounds, const char *text, int *active)
int GuiCheckBox(Rectangle bounds, const char *text, bool *checked)
int GuiComboBox(Rectangle bounds, const char *text, int *active)
int GuiDropdownBox(Rectangle bounds, const char *text, int *active, bool editMode)
int GuiSpinner(Rectangle bounds, const char *text, int *value, int minValue, int maxValue, bool editMode)
int GuiValueBox(Rectangle bounds, const char *text, int *value, int minValue, int maxValue, bool editMode)
int GuiTextBox(Rectangle bounds, char *text, int textSize, bool editMode)
int GuiSlider(Rectangle bounds, const char *textLeft, const char *textRight, float *value, float minValue, float maxValue)
int GuiSliderBar(Rectangle bounds, const char *textLeft, const char *textRight, float *value, float minValue, float maxValue)
int GuiProgressBar(Rectangle bounds, const char *textLeft, const char *textRight, float *value, float minValue, float maxValue)
int GuiStatusBar(Rectangle bounds, const char *text)
int GuiDummyRec(Rectangle bounds, const char *text)
int GuiGrid(Rectangle bounds, const char *text, float spacing, int subdivs, Vector2 *mouseCell)
int GuiListView(Rectangle bounds, const char *text, int *scrollIndex, int *active)
int GuiListViewEx(Rectangle bounds, const char **text, int count, int *scrollIndex, int *active, int *focus)
int GuiMessageBox(Rectangle bounds, const char *title, const char *message, const char *buttons)
int GuiTextInputBox(Rectangle bounds, const char *title, const char *message, const char *buttons, char *text, int textMaxSize, bool *secretViewActive)
int GuiColorPicker(Rectangle bounds, const char *text, Color *color)
int GuiColorPanel(Rectangle bounds, const char *text, Color *color)
int GuiColorBarAlpha(Rectangle bounds, const char *text, float *alpha)
int GuiColorBarHue(Rectangle bounds, const char *text, float *value)
int GuiColorPickerHSV(Rectangle bounds, const char *text, Vector3 *colorHsv)
int GuiColorPanelHSV(Rectangle bounds, const char *text, Vector3 *colorHsv)