const char *raylua_boot = "local ffi = require \"ffi\"" "\n"
"local raylib = {}" "\n"
"local raylib_so = ffi.load(\"raylib\")" "\n"
"" "\n"
"-- ffi cdef, based on raylib.h" "\n"
"ffi.cdef [[" "\n"
"  typedef struct Vector2 {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"  } Vector2;" "\n"
"  typedef struct Vector3 {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"    float z;" "\n"
"  } Vector3;" "\n"
"  typedef struct Vector4 {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"    float z;" "\n"
"    float w;" "\n"
"  } Vector4;" "\n"
"  typedef Vector4 Quaternion;" "\n"
"  typedef struct Matrix {" "\n"
"    float m0, m4, m8, m12;" "\n"
"    float m1, m5, m9, m13;" "\n"
"    float m2, m6, m10, m14;" "\n"
"    float m3, m7, m11, m15;" "\n"
"  } Matrix;" "\n"
"  typedef struct Color {" "\n"
"    unsigned char r;" "\n"
"    unsigned char g;" "\n"
"    unsigned char b;" "\n"
"    unsigned char a;" "\n"
"  } Color;" "\n"
"  typedef struct Rectangle {" "\n"
"    float x;" "\n"
"    float y;" "\n"
"    float width;" "\n"
"    float height;" "\n"
"  } Rectangle;" "\n"
"  typedef struct Image {" "\n"
"    void *data;" "\n"
"    int width;" "\n"
"    int height;" "\n"
"    int mipmaps;" "\n"
"    int format;" "\n"
"  } Image;" "\n"
"  typedef struct Texture2D {" "\n"
"    unsigned int id;" "\n"
"    int width;" "\n"
"    int height;" "\n"
"    int mipmaps;" "\n"
"    int format;" "\n"
"  } Texture2D;" "\n"
"  typedef Texture2D Texture;" "\n"
"  typedef Texture2D TextureCubemap;" "\n"
"  typedef struct RenderTexture2D {" "\n"
"    unsigned int id;" "\n"
"    Texture2D texture;" "\n"
"    Texture2D depth;" "\n"
"    bool depthTexture;" "\n"
"  } RenderTexture2D;" "\n"
"  typedef RenderTexture2D RenderTexture;" "\n"
"  typedef struct NPatchInfo {" "\n"
"    Rectangle sourceRec;" "\n"
"    int left;" "\n"
"    int top;" "\n"
"    int right;" "\n"
"    int bottom;" "\n"
"    int type;" "\n"
"  } NPatchInfo;" "\n"
"  typedef struct CharInfo {" "\n"
"    int value;" "\n"
"    int offsetX;" "\n"
"    int offsetY;" "\n"
"    int advanceX;" "\n"
"    Image image;" "\n"
"  } CharInfo;" "\n"
"  typedef struct Font {" "\n"
"    int baseSize;" "\n"
"    int charsCount;" "\n"
"    Texture2D texture;" "\n"
"    Rectangle *recs;" "\n"
"    CharInfo *chars;" "\n"
"  } Font;" "\n"
"" "\n"
"  typedef SpriteFont Font;" "\n"
"  typedef struct Camera3D {" "\n"
"    Vector3 position;" "\n"
"    Vector3 target;" "\n"
"    Vector3 up;" "\n"
"    float fovy;" "\n"
"    int type;" "\n"
"  } Camera3D;" "\n"
"" "\n"
"  typedef Camera3D Camera;" "\n"
"  typedef struct Camera2D {" "\n"
"    Vector2 offset;" "\n"
"    Vector2 target;" "\n"
"    float rotation;" "\n"
"    float zoom;" "\n"
"  } Camera2D;" "\n"
"  typedef struct Mesh {" "\n"
"    int vertexCount;" "\n"
"    int triangleCount;" "\n"
"    float *vertices;" "\n"
"    float *texcoords;" "\n"
"    float *texcoords2;" "\n"
"    float *normals;" "\n"
"    float *tangents;" "\n"
"    unsigned char *colors;" "\n"
"    unsigned short *indices;" "\n"
"    float *animVertices;" "\n"
"    float *animNormals;" "\n"
"    int *boneIds;" "\n"
"    float *boneWeights;" "\n"
"    unsigned int vaoId;" "\n"
"    unsigned int *vboId;" "\n"
"  } Mesh;" "\n"
"  typedef struct Shader {" "\n"
"    unsigned int id;" "\n"
"    int *locs;" "\n"
"  } Shader;" "\n"
"  typedef struct MaterialMap {" "\n"
"    Texture2D texture;" "\n"
"    Color color;" "\n"
"    float value;" "\n"
"  } MaterialMap;" "\n"
"  typedef struct Material {" "\n"
"    Shader shader;" "\n"
"    MaterialMap *maps;" "\n"
"    float *params;" "\n"
"  } Material;" "\n"
"  typedef struct Transform {" "\n"
"    Vector3 translation;" "\n"
"    Quaternion rotation;" "\n"
"    Vector3 scale;" "\n"
"  } Transform;" "\n"
"  typedef struct BoneInfo {" "\n"
"    char name[32];" "\n"
"    int parent;" "\n"
"  } BoneInfo;" "\n"
"  typedef struct Model {" "\n"
"    Matrix transform;" "\n"
"" "\n"
"    int meshCount;" "\n"
"    Mesh *meshes;" "\n"
"" "\n"
"    int materialCount;" "\n"
"    Material *materials;" "\n"
"    int *meshMaterial;" "\n"
"    int boneCount;" "\n"
"    BoneInfo *bones;" "\n"
"    Transform *bindPose;" "\n"
"  } Model;" "\n"
"  typedef struct ModelAnimation {" "\n"
"    int boneCount;" "\n"
"    BoneInfo *bones;" "\n"
"" "\n"
"    int frameCount;" "\n"
"    Transform **framePoses;" "\n"
"  } ModelAnimation;" "\n"
"  typedef struct Ray {" "\n"
"    Vector3 position;" "\n"
"    Vector3 direction;" "\n"
"  } Ray;" "\n"
"  typedef struct RayHitInfo {" "\n"
"    bool hit;" "\n"
"    float distance;" "\n"
"    Vector3 position;" "\n"
"    Vector3 normal;" "\n"
"  } RayHitInfo;" "\n"
"  typedef struct BoundingBox {" "\n"
"    Vector3 min;" "\n"
"    Vector3 max;" "\n"
"  } BoundingBox;" "\n"
"  typedef struct Wave {" "\n"
"    unsigned int sampleCount;" "\n"
"    unsigned int sampleRate;" "\n"
"    unsigned int sampleSize;" "\n"
"    unsigned int channels;" "\n"
"    void *data;" "\n"
"  } Wave;" "\n"
"" "\n"
"  typedef struct rAudioBuffer rAudioBuffer;" "\n"
"  typedef struct AudioStream {" "\n"
"    unsigned int sampleRate;" "\n"
"    unsigned int sampleSize;" "\n"
"    unsigned int channels;" "\n"
"" "\n"
"    rAudioBuffer *buffer;" "\n"
"  } AudioStream;" "\n"
"  typedef struct Sound {" "\n"
"    unsigned int sampleCount;" "\n"
"    AudioStream stream;" "\n"
"  } Sound;" "\n"
"  typedef struct Music {" "\n"
"    int ctxType;" "\n"
"    void *ctxData;" "\n"
"" "\n"
"    unsigned int sampleCount;" "\n"
"    unsigned int loopCount;" "\n"
"" "\n"
"    AudioStream stream;" "\n"
"  } Music;" "\n"
"  typedef struct VrDeviceInfo {" "\n"
"    int hResolution;" "\n"
"    int vResolution;" "\n"
"    float hScreenSize;" "\n"
"    float vScreenSize;" "\n"
"    float vScreenCenter;" "\n"
"    float eyeToScreenDistance;" "\n"
"    float lensSeparationDistance;" "\n"
"    float interpupillaryDistance;" "\n"
"    float lensDistortionValues[4];" "\n"
"    float chromaAbCorrection[4];" "\n"
"  } VrDeviceInfo;" "\n"
"  typedef enum {" "\n"
"    FLAG_RESERVED = 1," "\n"
"    FLAG_FULLSCREEN_MODE= 2," "\n"
"    FLAG_WINDOW_RESIZABLE = 4," "\n"
"    FLAG_WINDOW_UNDECORATED = 8," "\n"
"    FLAG_WINDOW_TRANSPARENT = 16," "\n"
"    FLAG_WINDOW_HIDDEN= 128," "\n"
"    FLAG_WINDOW_ALWAYS_RUN= 256," "\n"
"    FLAG_MSAA_4X_HINT = 32," "\n"
"    FLAG_VSYNC_HINT = 64" "\n"
"  } ConfigFlag;" "\n"
"  typedef enum {" "\n"
"    LOG_ALL = 0," "\n"
"    LOG_TRACE," "\n"
"    LOG_DEBUG," "\n"
"    LOG_INFO," "\n"
"    LOG_WARNING," "\n"
"    LOG_ERROR," "\n"
"    LOG_FATAL," "\n"
"    LOG_NONE" "\n"
"  } TraceLogType;" "\n"
"  typedef enum {" "\n"
"    KEY_APOSTROPHE= 39," "\n"
"    KEY_COMMA = 44," "\n"
"    KEY_MINUS = 45," "\n"
"    KEY_PERIOD= 46," "\n"
"    KEY_SLASH = 47," "\n"
"    KEY_ZERO  = 48," "\n"
"    KEY_ONE   = 49," "\n"
"    KEY_TWO   = 50," "\n"
"    KEY_THREE = 51," "\n"
"    KEY_FOUR  = 52," "\n"
"    KEY_FIVE  = 53," "\n"
"    KEY_SIX   = 54," "\n"
"    KEY_SEVEN = 55," "\n"
"    KEY_EIGHT = 56," "\n"
"    KEY_NINE  = 57," "\n"
"    KEY_SEMICOLON = 59," "\n"
"    KEY_EQUAL = 61," "\n"
"    KEY_A     = 65," "\n"
"    KEY_B     = 66," "\n"
"    KEY_C     = 67," "\n"
"    KEY_D     = 68," "\n"
"    KEY_E     = 69," "\n"
"    KEY_F     = 70," "\n"
"    KEY_G     = 71," "\n"
"    KEY_H     = 72," "\n"
"    KEY_I     = 73," "\n"
"    KEY_J     = 74," "\n"
"    KEY_K     = 75," "\n"
"    KEY_L     = 76," "\n"
"    KEY_M     = 77," "\n"
"    KEY_N     = 78," "\n"
"    KEY_O     = 79," "\n"
"    KEY_P     = 80," "\n"
"    KEY_Q     = 81," "\n"
"    KEY_R     = 82," "\n"
"    KEY_S     = 83," "\n"
"    KEY_T     = 84," "\n"
"    KEY_U     = 85," "\n"
"    KEY_V     = 86," "\n"
"    KEY_W     = 87," "\n"
"    KEY_X     = 88," "\n"
"    KEY_Y     = 89," "\n"
"    KEY_Z     = 90," "\n"
"    KEY_SPACE = 32," "\n"
"    KEY_ESCAPE= 256," "\n"
"    KEY_ENTER = 257," "\n"
"    KEY_TAB   = 258," "\n"
"    KEY_BACKSPACE = 259," "\n"
"    KEY_INSERT= 260," "\n"
"    KEY_DELETE= 261," "\n"
"    KEY_RIGHT = 262," "\n"
"    KEY_LEFT  = 263," "\n"
"    KEY_DOWN  = 264," "\n"
"    KEY_UP    = 265," "\n"
"    KEY_PAGE_UP = 266," "\n"
"    KEY_PAGE_DOWN = 267," "\n"
"    KEY_HOME  = 268," "\n"
"    KEY_END   = 269," "\n"
"    KEY_CAPS_LOCK = 280," "\n"
"    KEY_SCROLL_LOCK = 281," "\n"
"    KEY_NUM_LOCK= 282," "\n"
"    KEY_PRINT_SCREEN= 283," "\n"
"    KEY_PAUSE = 284," "\n"
"    KEY_F1    = 290," "\n"
"    KEY_F2    = 291," "\n"
"    KEY_F3    = 292," "\n"
"    KEY_F4    = 293," "\n"
"    KEY_F5    = 294," "\n"
"    KEY_F6    = 295," "\n"
"    KEY_F7    = 296," "\n"
"    KEY_F8    = 297," "\n"
"    KEY_F9    = 298," "\n"
"    KEY_F10   = 299," "\n"
"    KEY_F11   = 300," "\n"
"    KEY_F12   = 301," "\n"
"    KEY_LEFT_SHIFT= 340," "\n"
"    KEY_LEFT_CONTROL= 341," "\n"
"    KEY_LEFT_ALT= 342," "\n"
"    KEY_LEFT_SUPER= 343," "\n"
"    KEY_RIGHT_SHIFT = 344," "\n"
"    KEY_RIGHT_CONTROL = 345," "\n"
"    KEY_RIGHT_ALT = 346," "\n"
"    KEY_RIGHT_SUPER = 347," "\n"
"    KEY_KB_MENU = 348," "\n"
"    KEY_LEFT_BRACKET= 91," "\n"
"    KEY_BACKSLASH = 92," "\n"
"    KEY_RIGHT_BRACKET = 93," "\n"
"    KEY_GRAVE = 96," "\n"
"    KEY_KP_0  = 320," "\n"
"    KEY_KP_1  = 321," "\n"
"    KEY_KP_2  = 322," "\n"
"    KEY_KP_3  = 323," "\n"
"    KEY_KP_4  = 324," "\n"
"    KEY_KP_5  = 325," "\n"
"    KEY_KP_6  = 326," "\n"
"    KEY_KP_7  = 327," "\n"
"    KEY_KP_8  = 328," "\n"
"    KEY_KP_9  = 329," "\n"
"    KEY_KP_DECIMAL= 330," "\n"
"    KEY_KP_DIVIDE = 331," "\n"
"    KEY_KP_MULTIPLY = 332," "\n"
"    KEY_KP_SUBTRACT = 333," "\n"
"    KEY_KP_ADD= 334," "\n"
"    KEY_KP_ENTER= 335," "\n"
"    KEY_KP_EQUAL= 336" "\n"
"  } KeyboardKey;" "\n"
"  typedef enum {" "\n"
"    KEY_BACK  = 4," "\n"
"    KEY_MENU  = 82," "\n"
"    KEY_VOLUME_UP = 24," "\n"
"    KEY_VOLUME_DOWN = 25" "\n"
"  } AndroidButton;" "\n"
"  typedef enum {" "\n"
"    MOUSE_LEFT_BUTTON = 0," "\n"
"    MOUSE_RIGHT_BUTTON= 1," "\n"
"    MOUSE_MIDDLE_BUTTON = 2" "\n"
"  } MouseButton;" "\n"
"  typedef enum {" "\n"
"    GAMEPAD_PLAYER1 = 0," "\n"
"    GAMEPAD_PLAYER2 = 1," "\n"
"    GAMEPAD_PLAYER3 = 2," "\n"
"    GAMEPAD_PLAYER4 = 3" "\n"
"  } GamepadNumber;" "\n"
"  typedef enum {" "\n"
"    GAMEPAD_BUTTON_UNKNOWN = 0," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_UP," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_RIGHT," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_DOWN," "\n"
"    GAMEPAD_BUTTON_LEFT_FACE_LEFT," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_UP," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_RIGHT," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_DOWN," "\n"
"    GAMEPAD_BUTTON_RIGHT_FACE_LEFT," "\n"
"    GAMEPAD_BUTTON_LEFT_TRIGGER_1," "\n"
"    GAMEPAD_BUTTON_LEFT_TRIGGER_2," "\n"
"    GAMEPAD_BUTTON_RIGHT_TRIGGER_1," "\n"
"    GAMEPAD_BUTTON_RIGHT_TRIGGER_2," "\n"
"    GAMEPAD_BUTTON_MIDDLE_LEFT," "\n"
"    GAMEPAD_BUTTON_MIDDLE," "\n"
"    GAMEPAD_BUTTON_MIDDLE_RIGHT," "\n"
"    GAMEPAD_BUTTON_LEFT_THUMB," "\n"
"    GAMEPAD_BUTTON_RIGHT_THUMB" "\n"
"  } GamepadButton;" "\n"
"" "\n"
"  typedef enum {" "\n"
"    GAMEPAD_AXIS_UNKNOWN = 0," "\n"
"    GAMEPAD_AXIS_LEFT_X," "\n"
"    GAMEPAD_AXIS_LEFT_Y," "\n"
"    GAMEPAD_AXIS_RIGHT_X," "\n"
"    GAMEPAD_AXIS_RIGHT_Y," "\n"
"    GAMEPAD_AXIS_LEFT_TRIGGER," "\n"
"    GAMEPAD_AXIS_RIGHT_TRIGGER" "\n"
"  } GamepadAxis;" "\n"
"  typedef enum {" "\n"
"    LOC_VERTEX_POSITION = 0," "\n"
"    LOC_VERTEX_TEXCOORD01," "\n"
"    LOC_VERTEX_TEXCOORD02," "\n"
"    LOC_VERTEX_NORMAL," "\n"
"    LOC_VERTEX_TANGENT," "\n"
"    LOC_VERTEX_COLOR," "\n"
"    LOC_MATRIX_MVP," "\n"
"    LOC_MATRIX_MODEL," "\n"
"    LOC_MATRIX_VIEW," "\n"
"    LOC_MATRIX_PROJECTION," "\n"
"    LOC_VECTOR_VIEW," "\n"
"    LOC_COLOR_DIFFUSE," "\n"
"    LOC_COLOR_SPECULAR," "\n"
"    LOC_COLOR_AMBIENT," "\n"
"    LOC_MAP_ALBEDO," "\n"
"    LOC_MAP_METALNESS," "\n"
"    LOC_MAP_NORMAL," "\n"
"    LOC_MAP_ROUGHNESS," "\n"
"    LOC_MAP_OCCLUSION," "\n"
"    LOC_MAP_EMISSION," "\n"
"    LOC_MAP_HEIGHT," "\n"
"    LOC_MAP_CUBEMAP," "\n"
"    LOC_MAP_IRRADIANCE," "\n"
"    LOC_MAP_PREFILTER," "\n"
"    LOC_MAP_BRDF" "\n"
"  } ShaderLocationIndex;" "\n"
"" "\n"
"  #define LOC_MAP_DIFFUSE LOC_MAP_ALBEDO" "\n"
"  #define LOC_MAP_SPECULAR LOC_MAP_METALNESS" "\n"
"" "\n"
"  typedef enum {" "\n"
"    UNIFORM_FLOAT = 0," "\n"
"    UNIFORM_VEC2," "\n"
"    UNIFORM_VEC3," "\n"
"    UNIFORM_VEC4," "\n"
"    UNIFORM_INT," "\n"
"    UNIFORM_IVEC2," "\n"
"    UNIFORM_IVEC3," "\n"
"    UNIFORM_IVEC4," "\n"
"    UNIFORM_SAMPLER2D" "\n"
"  } ShaderUniformDataType;" "\n"
"  typedef enum {" "\n"
"    MAP_ALBEDO= 0," "\n"
"    MAP_METALNESS = 1," "\n"
"    MAP_NORMAL= 2," "\n"
"    MAP_ROUGHNESS = 3," "\n"
"    MAP_OCCLUSION," "\n"
"    MAP_EMISSION," "\n"
"    MAP_HEIGHT," "\n"
"    MAP_CUBEMAP," "\n"
"    MAP_IRRADIANCE," "\n"
"    MAP_PREFILTER," "\n"
"    MAP_BRDF" "\n"
"  } MaterialMapType;" "\n"
"" "\n"
"  #define MAP_DIFFUSE MAP_ALBEDO" "\n"
"  #define MAP_SPECULAR MAP_METALNESS" "\n"
"" "\n"
"  typedef enum {" "\n"
"    UNCOMPRESSED_GRAYSCALE = 1," "\n"
"    UNCOMPRESSED_GRAY_ALPHA," "\n"
"    UNCOMPRESSED_R5G6B5," "\n"
"    UNCOMPRESSED_R8G8B8," "\n"
"    UNCOMPRESSED_R5G5B5A1," "\n"
"    UNCOMPRESSED_R4G4B4A4," "\n"
"    UNCOMPRESSED_R8G8B8A8," "\n"
"    UNCOMPRESSED_R32," "\n"
"    UNCOMPRESSED_R32G32B32," "\n"
"    UNCOMPRESSED_R32G32B32A32," "\n"
"    COMPRESSED_DXT1_RGB," "\n"
"    COMPRESSED_DXT1_RGBA," "\n"
"    COMPRESSED_DXT3_RGBA," "\n"
"    COMPRESSED_DXT5_RGBA," "\n"
"    COMPRESSED_ETC1_RGB," "\n"
"    COMPRESSED_ETC2_RGB," "\n"
"    COMPRESSED_ETC2_EAC_RGBA," "\n"
"    COMPRESSED_PVRT_RGB," "\n"
"    COMPRESSED_PVRT_RGBA," "\n"
"    COMPRESSED_ASTC_4x4_RGBA," "\n"
"    COMPRESSED_ASTC_8x8_RGBA" "\n"
"  } PixelFormat;" "\n"
"  typedef enum {" "\n"
"    FILTER_POINT = 0," "\n"
"    FILTER_BILINEAR," "\n"
"    FILTER_TRILINEAR," "\n"
"    FILTER_ANISOTROPIC_4X," "\n"
"    FILTER_ANISOTROPIC_8X," "\n"
"    FILTER_ANISOTROPIC_16X," "\n"
"  } TextureFilterMode;" "\n"
"  typedef enum {" "\n"
"    CUBEMAP_AUTO_DETECT = 0," "\n"
"    CUBEMAP_LINE_VERTICAL," "\n"
"    CUBEMAP_LINE_HORIZONTAL," "\n"
"    CUBEMAP_CROSS_THREE_BY_FOUR," "\n"
"    CUBEMAP_CROSS_FOUR_BY_THREE," "\n"
"    CUBEMAP_PANORAMA" "\n"
"  } CubemapLayoutType;" "\n"
"  typedef enum {" "\n"
"    WRAP_REPEAT = 0," "\n"
"    WRAP_CLAMP," "\n"
"    WRAP_MIRROR_REPEAT," "\n"
"    WRAP_MIRROR_CLAMP" "\n"
"  } TextureWrapMode;" "\n"
"  typedef enum {" "\n"
"    FONT_DEFAULT = 0," "\n"
"    FONT_BITMAP," "\n"
"    FONT_SDF" "\n"
"  } FontType;" "\n"
"  typedef enum {" "\n"
"    BLEND_ALPHA = 0," "\n"
"    BLEND_ADDITIVE," "\n"
"    BLEND_MULTIPLIED" "\n"
"  } BlendMode;" "\n"
"  typedef enum {" "\n"
"    GESTURE_NONE = 0," "\n"
"    GESTURE_TAP = 1," "\n"
"    GESTURE_DOUBLETAP = 2," "\n"
"    GESTURE_HOLD= 4," "\n"
"    GESTURE_DRAG= 8," "\n"
"    GESTURE_SWIPE_RIGHT = 16," "\n"
"    GESTURE_SWIPE_LEFT= 32," "\n"
"    GESTURE_SWIPE_UP= 64," "\n"
"    GESTURE_SWIPE_DOWN= 128," "\n"
"    GESTURE_PINCH_IN= 256," "\n"
"    GESTURE_PINCH_OUT = 512" "\n"
"  } GestureType;" "\n"
"  typedef enum {" "\n"
"    CAMERA_CUSTOM = 0," "\n"
"    CAMERA_FREE," "\n"
"    CAMERA_ORBITAL," "\n"
"    CAMERA_FIRST_PERSON," "\n"
"    CAMERA_THIRD_PERSON" "\n"
"  } CameraMode;" "\n"
"  typedef enum {" "\n"
"    CAMERA_PERSPECTIVE = 0," "\n"
"    CAMERA_ORTHOGRAPHIC" "\n"
"  } CameraType;" "\n"
"  typedef enum {" "\n"
"    NPT_9PATCH = 0," "\n"
"    NPT_3PATCH_VERTICAL," "\n"
"    NPT_3PATCH_HORIZONTAL" "\n"
"  } NPatchType;" "\n"
"  typedef void (*TraceLogCallback)(int logType, const char *text, va_list args);" "\n"
"" "\n"
"  void InitWindow(int width, int height, const char *title);" "\n"
"  bool WindowShouldClose(void);" "\n"
"  void CloseWindow(void);" "\n"
"  bool IsWindowReady(void);" "\n"
"  bool IsWindowMinimized(void);" "\n"
"  bool IsWindowResized(void);" "\n"
"  bool IsWindowHidden(void);" "\n"
"  void ToggleFullscreen(void);" "\n"
"  void UnhideWindow(void);" "\n"
"  void HideWindow(void);" "\n"
"  void SetWindowIcon(Image image);" "\n"
"  void SetWindowTitle(const char *title);" "\n"
"  void SetWindowPosition(int x, int y);" "\n"
"  void SetWindowMonitor(int monitor);" "\n"
"  void SetWindowMinSize(int width, int height);" "\n"
"  void SetWindowSize(int width, int height);" "\n"
"  void *GetWindowHandle(void);" "\n"
"  int GetScreenWidth(void);" "\n"
"  int GetScreenHeight(void);" "\n"
"  int GetMonitorCount(void);" "\n"
"  int GetMonitorWidth(int monitor);" "\n"
"  int GetMonitorHeight(int monitor);" "\n"
"  int GetMonitorPhysicalWidth(int monitor);" "\n"
"  int GetMonitorPhysicalHeight(int monitor);" "\n"
"  Vector2 GetWindowPosition(void);" "\n"
"  const char *GetMonitorName(int monitor);" "\n"
"  const char *GetClipboardText(void);" "\n"
"  void SetClipboardText(const char *text);" "\n"
"  void ShowCursor(void);" "\n"
"  void HideCursor(void);" "\n"
"  bool IsCursorHidden(void);" "\n"
"  void EnableCursor(void);" "\n"
"  void DisableCursor(void);" "\n"
"  void ClearBackground(Color color);" "\n"
"  void BeginDrawing(void);" "\n"
"  void EndDrawing(void);" "\n"
"  void BeginMode2D(Camera2D camera);" "\n"
"  void EndMode2D(void);" "\n"
"  void BeginMode3D(Camera3D camera);" "\n"
"  void EndMode3D(void);" "\n"
"  void BeginTextureMode(RenderTexture2D target);" "\n"
"  void EndTextureMode(void);" "\n"
"  void BeginScissorMode(int x, int y, int width, int height);" "\n"
"  void EndScissorMode(void);" "\n"
"  Ray GetMouseRay(Vector2 mousePosition, Camera camera);" "\n"
"  Matrix GetCameraMatrix(Camera camera);" "\n"
"  Matrix GetCameraMatrix2D(Camera2D camera);" "\n"
"  Vector2 GetWorldToScreen(Vector3 position, Camera camera);" "\n"
"  Vector2 GetWorldToScreenEx(Vector3 position, Camera camera, int width, int height);" "\n"
"  Vector2 GetWorldToScreen2D(Vector2 position, Camera2D camera);" "\n"
"  Vector2 GetScreenToWorld2D(Vector2 position, Camera2D camera);" "\n"
"  void SetTargetFPS(int fps);" "\n"
"  int GetFPS(void);" "\n"
"  float GetFrameTime(void);" "\n"
"  double GetTime(void);" "\n"
"  int ColorToInt(Color color);" "\n"
"  Vector4 ColorNormalize(Color color);" "\n"
"  Color ColorFromNormalized(Vector4 normalized);" "\n"
"  Vector3 ColorToHSV(Color color);" "\n"
"  Color ColorFromHSV(Vector3 hsv);" "\n"
"  Color GetColor(int hexValue);" "\n"
"  Color Fade(Color color, float alpha);" "\n"
"  void SetConfigFlags(unsigned int flags);" "\n"
"  void SetTraceLogLevel(int logType);" "\n"
"  void SetTraceLogExit(int logType);" "\n"
"  void SetTraceLogCallback(TraceLogCallback callback);" "\n"
"  void TraceLog(int logType, const char *text, ...);" "\n"
"  void TakeScreenshot(const char *fileName);" "\n"
"  int GetRandomValue(int min, int max);" "\n"
"  unsigned char *LoadFileData(const char *fileName, int *bytesRead);" "\n"
"  void SaveFileData(const char *fileName, void *data, int bytesToWrite);" "\n"
"  bool FileExists(const char *fileName);" "\n"
"  bool IsFileExtension(const char *fileName, const char *ext);" "\n"
"  bool DirectoryExists(const char *dirPath);" "\n"
"  const char *GetExtension(const char *fileName);" "\n"
"  const char *GetFileName(const char *filePath);" "\n"
"  const char *GetFileNameWithoutExt(const char *filePath);" "\n"
"  const char *GetDirectoryPath(const char *filePath);" "\n"
"  const char *GetPrevDirectoryPath(const char *dirPath);" "\n"
"  const char *GetWorkingDirectory(void);" "\n"
"  char **GetDirectoryFiles(const char *dirPath, int *count);" "\n"
"  void ClearDirectoryFiles(void);" "\n"
"  bool ChangeDirectory(const char *dir);" "\n"
"  bool IsFileDropped(void);" "\n"
"  char **GetDroppedFiles(int *count);" "\n"
"  void ClearDroppedFiles(void);" "\n"
"  long GetFileModTime(const char *fileName);" "\n"
"" "\n"
"  unsigned char *CompressData(unsigned char *data, int dataLength, int *compDataLength);" "\n"
"  unsigned char *DecompressData(unsigned char *compData, int compDataLength, int *dataLength);" "\n"
"  void StorageSaveValue(int position, int value);" "\n"
"  int StorageLoadValue(int position);" "\n"
"" "\n"
"  void OpenURL(const char *url);" "\n"
"  bool IsKeyPressed(int key);" "\n"
"  bool IsKeyDown(int key);" "\n"
"  bool IsKeyReleased(int key);" "\n"
"  bool IsKeyUp(int key);" "\n"
"  void SetExitKey(int key);" "\n"
"  int GetKeyPressed(void);" "\n"
"  bool IsGamepadAvailable(int gamepad);" "\n"
"  bool IsGamepadName(int gamepad, const char *name);" "\n"
"  const char *GetGamepadName(int gamepad);" "\n"
"  bool IsGamepadButtonPressed(int gamepad, int button);" "\n"
"  bool IsGamepadButtonDown(int gamepad, int button);" "\n"
"  bool IsGamepadButtonReleased(int gamepad, int button);" "\n"
"  bool IsGamepadButtonUp(int gamepad, int button);" "\n"
"  int GetGamepadButtonPressed(void);" "\n"
"  int GetGamepadAxisCount(int gamepad);" "\n"
"  float GetGamepadAxisMovement(int gamepad, int axis);" "\n"
"  bool IsMouseButtonPressed(int button);" "\n"
"  bool IsMouseButtonDown(int button);" "\n"
"  bool IsMouseButtonReleased(int button);" "\n"
"  bool IsMouseButtonUp(int button);" "\n"
"  int GetMouseX(void);" "\n"
"  int GetMouseY(void);" "\n"
"  Vector2 GetMousePosition(void);" "\n"
"  void SetMousePosition(int x, int y);" "\n"
"  void SetMouseOffset(int offsetX, int offsetY);" "\n"
"  void SetMouseScale(float scaleX, float scaleY);" "\n"
"  int GetMouseWheelMove(void);" "\n"
"  int GetTouchX(void);" "\n"
"  int GetTouchY(void);" "\n"
"  Vector2 GetTouchPosition(int index);" "\n"
"  void SetGesturesEnabled(unsigned int gestureFlags);" "\n"
"  bool IsGestureDetected(int gesture);" "\n"
"  int GetGestureDetected(void);" "\n"
"  int GetTouchPointsCount(void);" "\n"
"  float GetGestureHoldDuration(void);" "\n"
"  Vector2 GetGestureDragVector(void);" "\n"
"  float GetGestureDragAngle(void);" "\n"
"  Vector2 GetGesturePinchVector(void);" "\n"
"  float GetGesturePinchAngle(void);" "\n"
"  void SetCameraMode(Camera camera, int mode);" "\n"
"  void UpdateCamera(Camera *camera);" "\n"
"" "\n"
"  void SetCameraPanControl(int panKey);" "\n"
"  void SetCameraAltControl(int altKey);" "\n"
"  void SetCameraSmoothZoomControl(int szKey);" "\n"
"  void SetCameraMoveControls(int frontKey, int backKey, int rightKey, int leftKey, int upKey, int downKey);" "\n"
"  void DrawPixel(int posX, int posY, Color color);" "\n"
"  void DrawPixelV(Vector2 position, Color color);" "\n"
"  void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color);" "\n"
"  void DrawLineV(Vector2 startPos, Vector2 endPos, Color color);" "\n"
"  void DrawLineEx(Vector2 startPos, Vector2 endPos, float thick, Color color);" "\n"
"  void DrawLineBezier(Vector2 startPos, Vector2 endPos, float thick, Color color);" "\n"
"  void DrawLineStrip(Vector2 *points, int numPoints, Color color);" "\n"
"  void DrawCircle(int centerX, int centerY, float radius, Color color);" "\n"
"  void DrawCircleSector(Vector2 center, float radius, int startAngle, int endAngle, int segments, Color color);" "\n"
"  void DrawCircleSectorLines(Vector2 center, float radius, int startAngle, int endAngle, int segments, Color color);" "\n"
"  void DrawCircleGradient(int centerX, int centerY, float radius, Color color1, Color color2);" "\n"
"  void DrawCircleV(Vector2 center, float radius, Color color);" "\n"
"  void DrawCircleLines(int centerX, int centerY, float radius, Color color);" "\n"
"  void DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, Color color);" "\n"
"  void DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, Color color);" "\n"
"  void DrawRing(Vector2 center, float innerRadius, float outerRadius, int startAngle, int endAngle, int segments, Color color);" "\n"
"  void DrawRingLines(Vector2 center, float innerRadius, float outerRadius, int startAngle, int endAngle, int segments, Color color);" "\n"
"  void DrawRectangle(int posX, int posY, int width, int height, Color color);" "\n"
"  void DrawRectangleV(Vector2 position, Vector2 size, Color color);" "\n"
"  void DrawRectangleRec(Rectangle rec, Color color);" "\n"
"  void DrawRectanglePro(Rectangle rec, Vector2 origin, float rotation, Color color);" "\n"
"  void DrawRectangleGradientV(int posX, int posY, int width, int height, Color color1, Color color2);" "\n"
"  void DrawRectangleGradientH(int posX, int posY, int width, int height, Color color1, Color color2);" "\n"
"  void DrawRectangleGradientEx(Rectangle rec, Color col1, Color col2, Color col3, Color col4);" "\n"
"  void DrawRectangleLines(int posX, int posY, int width, int height, Color color);" "\n"
"  void DrawRectangleLinesEx(Rectangle rec, int lineThick, Color color);" "\n"
"  void DrawRectangleRounded(Rectangle rec, float roundness, int segments, Color color);" "\n"
"  void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, int lineThick, Color color);" "\n"
"  void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color);" "\n"
"  void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color);" "\n"
"  void DrawTriangleFan(Vector2 *points, int numPoints, Color color);" "\n"
"  void DrawTriangleStrip(Vector2 *points, int pointsCount, Color color);" "\n"
"  void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color);" "\n"
"  void DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color);" "\n"
"  bool CheckCollisionRecs(Rectangle rec1, Rectangle rec2);" "\n"
"  bool CheckCollisionCircles(Vector2 center1, float radius1, Vector2 center2, float radius2);" "\n"
"  bool CheckCollisionCircleRec(Vector2 center, float radius, Rectangle rec);" "\n"
"  Rectangle GetCollisionRec(Rectangle rec1, Rectangle rec2);" "\n"
"  bool CheckCollisionPointRec(Vector2 point, Rectangle rec);" "\n"
"  bool CheckCollisionPointCircle(Vector2 point, Vector2 center, float radius);" "\n"
"  bool CheckCollisionPointTriangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3);" "\n"
"  Image LoadImage(const char *fileName);" "\n"
"  Image LoadImageEx(Color *pixels, int width, int height);" "\n"
"  Image LoadImagePro(void *data, int width, int height, int format);" "\n"
"  Image LoadImageRaw(const char *fileName, int width, int height, int format, int headerSize);" "\n"
"  void ExportImage(Image image, const char *fileName);" "\n"
"  void ExportImageAsCode(Image image, const char *fileName);" "\n"
"  Texture2D LoadTexture(const char *fileName);" "\n"
"  Texture2D LoadTextureFromImage(Image image);" "\n"
"  TextureCubemap LoadTextureCubemap(Image image, int layoutType);" "\n"
"  RenderTexture2D LoadRenderTexture(int width, int height);" "\n"
"  void UnloadImage(Image image);" "\n"
"  void UnloadTexture(Texture2D texture);" "\n"
"  void UnloadRenderTexture(RenderTexture2D target);" "\n"
"  Color *GetImageData(Image image);" "\n"
"  Vector4 *GetImageDataNormalized(Image image);" "\n"
"  Rectangle GetImageAlphaBorder(Image image, float threshold);" "\n"
"  int GetPixelDataSize(int width, int height, int format);" "\n"
"  Image GetTextureData(Texture2D texture);" "\n"
"  Image GetScreenData(void);" "\n"
"  void UpdateTexture(Texture2D texture, const void *pixels);" "\n"
"  Image ImageCopy(Image image);" "\n"
"  Image ImageFromImage(Image image, Rectangle rec);" "\n"
"  void ImageToPOT(Image *image, Color fillColor);" "\n"
"  void ImageFormat(Image *image, int newFormat);" "\n"
"  void ImageAlphaMask(Image *image, Image alphaMask);" "\n"
"  void ImageAlphaClear(Image *image, Color color, float threshold);" "\n"
"  void ImageAlphaCrop(Image *image, float threshold);" "\n"
"  void ImageAlphaPremultiply(Image *image);" "\n"
"  void ImageCrop(Image *image, Rectangle crop);" "\n"
"  void ImageResize(Image *image, int newWidth, int newHeight);" "\n"
"  void ImageResizeNN(Image *image, int newWidth,int newHeight);" "\n"
"  void ImageResizeCanvas(Image *image, int newWidth, int newHeight, int offsetX, int offsetY, Color color);" "\n"
"  void ImageMipmaps(Image *image);" "\n"
"  void ImageDither(Image *image, int rBpp, int gBpp, int bBpp, int aBpp);" "\n"
"  Color *ImageExtractPalette(Image image, int maxPaletteSize, int *extractCount);" "\n"
"  Image ImageText(const char *text, int fontSize, Color color);" "\n"
"  Image ImageTextEx(Font font, const char *text, float fontSize, float spacing, Color tint);" "\n"
"  void ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint);" "\n"
"  void ImageDrawRectangle(Image *dst, Rectangle rec, Color color);" "\n"
"  void ImageDrawRectangleLines(Image *dst, Rectangle rec, int thick, Color color);" "\n"
"  void ImageDrawText(Image *dst, Vector2 position, const char *text, int fontSize, Color color);" "\n"
"  void ImageDrawTextEx(Image *dst, Vector2 position, Font font, const char *text, float fontSize, float spacing, Color color);" "\n"
"  void ImageFlipVertical(Image *image);" "\n"
"  void ImageFlipHorizontal(Image *image);" "\n"
"  void ImageRotateCW(Image *image);" "\n"
"  void ImageRotateCCW(Image *image);" "\n"
"  void ImageColorTint(Image *image, Color color);" "\n"
"  void ImageColorInvert(Image *image);" "\n"
"  void ImageColorGrayscale(Image *image);" "\n"
"  void ImageColorContrast(Image *image, float contrast);" "\n"
"  void ImageColorBrightness(Image *image, int brightness);" "\n"
"  void ImageColorReplace(Image *image, Color color, Color replace);" "\n"
"  Image GenImageColor(int width, int height, Color color);" "\n"
"  Image GenImageGradientV(int width, int height, Color top, Color bottom);" "\n"
"  Image GenImageGradientH(int width, int height, Color left, Color right);" "\n"
"  Image GenImageGradientRadial(int width, int height, float density, Color inner, Color outer);" "\n"
"  Image GenImageChecked(int width, int height, int checksX, int checksY, Color col1, Color col2);" "\n"
"  Image GenImageWhiteNoise(int width, int height, float factor);" "\n"
"  Image GenImagePerlinNoise(int width, int height, int offsetX, int offsetY, float scale);" "\n"
"  Image GenImageCellular(int width, int height, int tileSize);" "\n"
"  void GenTextureMipmaps(Texture2D *texture);" "\n"
"  void SetTextureFilter(Texture2D texture, int filterMode);" "\n"
"  void SetTextureWrap(Texture2D texture, int wrapMode);" "\n"
"  void DrawTexture(Texture2D texture, int posX, int posY, Color tint);" "\n"
"  void DrawTextureV(Texture2D texture, Vector2 position, Color tint);" "\n"
"  void DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint);" "\n"
"  void DrawTextureRec(Texture2D texture, Rectangle sourceRec, Vector2 position, Color tint);" "\n"
"  void DrawTextureQuad(Texture2D texture, Vector2 tiling, Vector2 offset, Rectangle quad, Color tint);" "\n"
"  void DrawTexturePro(Texture2D texture, Rectangle sourceRec, Rectangle destRec, Vector2 origin, float rotation, Color tint);" "\n"
"  void DrawTextureNPatch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle destRec, Vector2 origin, float rotation, Color tint);" "\n"
"  Font GetFontDefault(void);" "\n"
"  Font LoadFont(const char *fileName);" "\n"
"  Font LoadFontEx(const char *fileName, int fontSize, int *fontChars, int charsCount);" "\n"
"  Font LoadFontFromImage(Image image, Color key, int firstChar);" "\n"
"  CharInfo *LoadFontData(const char *fileName, int fontSize, int *fontChars, int charsCount, int type);" "\n"
"  Image GenImageFontAtlas(const CharInfo *chars, Rectangle **recs, int charsCount, int fontSize, int padding, int packMethod);" "\n"
"  void UnloadFont(Font font);" "\n"
"  void DrawFPS(int posX, int posY);" "\n"
"  void DrawText(const char *text, int posX, int posY, int fontSize, Color color);" "\n"
"  void DrawTextEx(Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint);" "\n"
"  void DrawTextRec(Font font, const char *text, Rectangle rec, float fontSize, float spacing, bool wordWrap, Color tint);" "\n"
"  void DrawTextRecEx(Font font, const char *text, Rectangle rec, float fontSize, float spacing, bool wordWrap, Color tint," "\n"
"                           int selectStart, int selectLength, Color selectTint, Color selectBackTint);" "\n"
"  void DrawTextCodepoint(Font font, int codepoint, Vector2 position, float scale, Color tint);" "\n"
"  int MeasureText(const char *text, int fontSize);" "\n"
"  Vector2 MeasureTextEx(Font font, const char *text, float fontSize, float spacing);" "\n"
"  int GetGlyphIndex(Font font, int codepoint);" "\n"
"  int TextCopy(char *dst, const char *src);" "\n"
"  bool TextIsEqual(const char *text1, const char *text2);" "\n"
"  unsigned int TextLength(const char *text);" "\n"
"  const char *TextFormat(const char *text, ...);" "\n"
"  const char *TextSubtext(const char *text, int position, int length);" "\n"
"  char *TextReplace(char *text, const char *replace, const char *by);" "\n"
"  char *TextInsert(const char *text, const char *insert, int position);" "\n"
"  const char *TextJoin(const char **textList, int count, const char *delimiter);" "\n"
"  const char **TextSplit(const char *text, char delimiter, int *count);" "\n"
"  void TextAppend(char *text, const char *append, int *position);" "\n"
"  int TextFindIndex(const char *text, const char *find);" "\n"
"  const char *TextToUpper(const char *text);" "\n"
"  const char *TextToLower(const char *text);" "\n"
"  const char *TextToPascal(const char *text);" "\n"
"  int TextToInteger(const char *text);" "\n"
"  char *TextToUtf8(int *codepoints, int length);" "\n"
"  int *GetCodepoints(const char *text, int *count);" "\n"
"  int GetCodepointsCount(const char *text);" "\n"
"  int GetNextCodepoint(const char *text, int *bytesProcessed);" "\n"
"  const char *CodepointToUtf8(int codepoint, int *byteLength);" "\n"
"  void DrawLine3D(Vector3 startPos, Vector3 endPos, Color color);" "\n"
"  void DrawPoint3D(Vector3 position, Color color);" "\n"
"  void DrawCircle3D(Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color);" "\n"
"  void DrawCube(Vector3 position, float width, float height, float length, Color color);" "\n"
"  void DrawCubeV(Vector3 position, Vector3 size, Color color);" "\n"
"  void DrawCubeWires(Vector3 position, float width, float height, float length, Color color);" "\n"
"  void DrawCubeWiresV(Vector3 position, Vector3 size, Color color);" "\n"
"  void DrawCubeTexture(Texture2D texture, Vector3 position, float width, float height, float length, Color color);" "\n"
"  void DrawSphere(Vector3 centerPos, float radius, Color color);" "\n"
"  void DrawSphereEx(Vector3 centerPos, float radius, int rings, int slices, Color color);" "\n"
"  void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color);" "\n"
"  void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);" "\n"
"  void DrawCylinderWires(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color);" "\n"
"  void DrawPlane(Vector3 centerPos, Vector2 size, Color color);" "\n"
"  void DrawRay(Ray ray, Color color);" "\n"
"  void DrawGrid(int slices, float spacing);" "\n"
"  void DrawGizmo(Vector3 position);" "\n"
"  Model LoadModel(const char *fileName);" "\n"
"  Model LoadModelFromMesh(Mesh mesh);" "\n"
"  void UnloadModel(Model model);" "\n"
"  Mesh *LoadMeshes(const char *fileName, int *meshCount);" "\n"
"  void ExportMesh(Mesh mesh, const char *fileName);" "\n"
"  void UnloadMesh(Mesh mesh);" "\n"
"  Material *LoadMaterials(const char *fileName, int *materialCount);" "\n"
"  Material LoadMaterialDefault(void);" "\n"
"  void UnloadMaterial(Material material);" "\n"
"  void SetMaterialTexture(Material *material, int mapType, Texture2D texture);" "\n"
"  void SetModelMeshMaterial(Model *model, int meshId, int materialId);" "\n"
"  ModelAnimation *LoadModelAnimations(const char *fileName, int *animsCount);" "\n"
"  void UpdateModelAnimation(Model model, ModelAnimation anim, int frame);" "\n"
"  void UnloadModelAnimation(ModelAnimation anim);" "\n"
"  bool IsModelAnimationValid(Model model, ModelAnimation anim);" "\n"
"  Mesh GenMeshPoly(int sides, float radius);" "\n"
"  Mesh GenMeshPlane(float width, float length, int resX, int resZ);" "\n"
"  Mesh GenMeshCube(float width, float height, float length);" "\n"
"  Mesh GenMeshSphere(float radius, int rings, int slices);" "\n"
"  Mesh GenMeshHemiSphere(float radius, int rings, int slices);" "\n"
"  Mesh GenMeshCylinder(float radius, float height, int slices);" "\n"
"  Mesh GenMeshTorus(float radius, float size, int radSeg, int sides);" "\n"
"  Mesh GenMeshKnot(float radius, float size, int radSeg, int sides);" "\n"
"  Mesh GenMeshHeightmap(Image heightmap, Vector3 size);" "\n"
"  Mesh GenMeshCubicmap(Image cubicmap, Vector3 cubeSize);" "\n"
"  BoundingBox MeshBoundingBox(Mesh mesh);" "\n"
"  void MeshTangents(Mesh *mesh);" "\n"
"  void MeshBinormals(Mesh *mesh);" "\n"
"  void DrawModel(Model model, Vector3 position, float scale, Color tint);" "\n"
"  void DrawModelEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);" "\n"
"  void DrawModelWires(Model model, Vector3 position, float scale, Color tint);" "\n"
"  void DrawModelWiresEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint);" "\n"
"  void DrawBoundingBox(BoundingBox box, Color color);" "\n"
"  void DrawBillboard(Camera camera, Texture2D texture, Vector3 center, float size, Color tint);" "\n"
"  void DrawBillboardRec(Camera camera, Texture2D texture, Rectangle sourceRec, Vector3 center, float size, Color tint);" "\n"
"  bool CheckCollisionSpheres(Vector3 centerA, float radiusA, Vector3 centerB, float radiusB);" "\n"
"  bool CheckCollisionBoxes(BoundingBox box1, BoundingBox box2);" "\n"
"  bool CheckCollisionBoxSphere(BoundingBox box, Vector3 center, float radius);" "\n"
"  bool CheckCollisionRaySphere(Ray ray, Vector3 center, float radius);" "\n"
"  bool CheckCollisionRaySphereEx(Ray ray, Vector3 center, float radius, Vector3 *collisionPoint);" "\n"
"  bool CheckCollisionRayBox(Ray ray, BoundingBox box);" "\n"
"  RayHitInfo GetCollisionRayModel(Ray ray, Model model);" "\n"
"  RayHitInfo GetCollisionRayTriangle(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3);" "\n"
"  RayHitInfo GetCollisionRayGround(Ray ray, float groundHeight);" "\n"
"  char *LoadText(const char *fileName);" "\n"
"  Shader LoadShader(const char *vsFileName, const char *fsFileName);" "\n"
"  Shader LoadShaderCode(const char *vsCode, const char *fsCode);" "\n"
"  void UnloadShader(Shader shader);" "\n"
"  Shader GetShaderDefault(void);" "\n"
"  Texture2D GetTextureDefault(void);" "\n"
"  Texture2D GetShapesTexture(void);" "\n"
"  Rectangle GetShapesTextureRec(void);" "\n"
"  void SetShapesTexture(Texture2D texture, Rectangle source);" "\n"
"  int GetShaderLocation(Shader shader, const char *uniformName);" "\n"
"  void SetShaderValue(Shader shader, int uniformLoc, const void *value, int uniformType);" "\n"
"  void SetShaderValueV(Shader shader, int uniformLoc, const void *value, int uniformType, int count);" "\n"
"  void SetShaderValueMatrix(Shader shader, int uniformLoc, Matrix mat);" "\n"
"  void SetShaderValueTexture(Shader shader, int uniformLoc, Texture2D texture);" "\n"
"  void SetMatrixProjection(Matrix proj);" "\n"
"  void SetMatrixModelview(Matrix view);" "\n"
"  Matrix GetMatrixModelview(void);" "\n"
"  Matrix GetMatrixProjection(void);" "\n"
"  Texture2D GenTextureCubemap(Shader shader, Texture2D map, int size);" "\n"
"  Texture2D GenTextureIrradiance(Shader shader, Texture2D cubemap, int size);" "\n"
"  Texture2D GenTexturePrefilter(Shader shader, Texture2D cubemap, int size);" "\n"
"  Texture2D GenTextureBRDF(Shader shader, int size);" "\n"
"  void BeginShaderMode(Shader shader);" "\n"
"  void EndShaderMode(void);" "\n"
"  void BeginBlendMode(int mode);" "\n"
"  void EndBlendMode(void);" "\n"
"  void InitVrSimulator(void);" "\n"
"  void CloseVrSimulator(void);" "\n"
"  void UpdateVrTracking(Camera *camera);" "\n"
"  void SetVrConfiguration(VrDeviceInfo info, Shader distortion);" "\n"
"  bool IsVrSimulatorReady(void);" "\n"
"  void ToggleVrMode(void);" "\n"
"  void BeginVrDrawing(void);" "\n"
"  void EndVrDrawing(void);" "\n"
"  void InitAudioDevice(void);" "\n"
"  void CloseAudioDevice(void);" "\n"
"  bool IsAudioDeviceReady(void);" "\n"
"  void SetMasterVolume(float volume);" "\n"
"  Wave LoadWave(const char *fileName);" "\n"
"  Sound LoadSound(const char *fileName);" "\n"
"  Sound LoadSoundFromWave(Wave wave);" "\n"
"  void UpdateSound(Sound sound, const void *data, int samplesCount);" "\n"
"  void UnloadWave(Wave wave);" "\n"
"  void UnloadSound(Sound sound);" "\n"
"  void ExportWave(Wave wave, const char *fileName);" "\n"
"  void ExportWaveAsCode(Wave wave, const char *fileName);" "\n"
"  void PlaySound(Sound sound);" "\n"
"  void StopSound(Sound sound);" "\n"
"  void PauseSound(Sound sound);" "\n"
"  void ResumeSound(Sound sound);" "\n"
"  void PlaySoundMulti(Sound sound);" "\n"
"  void StopSoundMulti(void);" "\n"
"  int GetSoundsPlaying(void);" "\n"
"  bool IsSoundPlaying(Sound sound);" "\n"
"  void SetSoundVolume(Sound sound, float volume);" "\n"
"  void SetSoundPitch(Sound sound, float pitch);" "\n"
"  void WaveFormat(Wave *wave, int sampleRate, int sampleSize, int channels);" "\n"
"  Wave WaveCopy(Wave wave);" "\n"
"  void WaveCrop(Wave *wave, int initSample, int finalSample);" "\n"
"  float *GetWaveData(Wave wave);" "\n"
"  Music LoadMusicStream(const char *fileName);" "\n"
"  void UnloadMusicStream(Music music);" "\n"
"  void PlayMusicStream(Music music);" "\n"
"  void UpdateMusicStream(Music music);" "\n"
"  void StopMusicStream(Music music);" "\n"
"  void PauseMusicStream(Music music);" "\n"
"  void ResumeMusicStream(Music music);" "\n"
"  bool IsMusicPlaying(Music music);" "\n"
"  void SetMusicVolume(Music music, float volume);" "\n"
"  void SetMusicPitch(Music music, float pitch);" "\n"
"  void SetMusicLoopCount(Music music, int count);" "\n"
"  float GetMusicTimeLength(Music music);" "\n"
"  float GetMusicTimePlayed(Music music);" "\n"
"  AudioStream InitAudioStream(unsigned int sampleRate, unsigned int sampleSize, unsigned int channels);" "\n"
"  void UpdateAudioStream(AudioStream stream, const void *data, int samplesCount);" "\n"
"  void CloseAudioStream(AudioStream stream);" "\n"
"  bool IsAudioStreamProcessed(AudioStream stream);" "\n"
"  void PlayAudioStream(AudioStream stream);" "\n"
"  void PauseAudioStream(AudioStream stream);" "\n"
"  void ResumeAudioStream(AudioStream stream);" "\n"
"  bool IsAudioStreamPlaying(AudioStream stream);" "\n"
"  void StopAudioStream(AudioStream stream);" "\n"
"  void SetAudioStreamVolume(AudioStream stream, float volume);" "\n"
"  void SetAudioStreamPitch(AudioStream stream, float pitch);" "\n"
"  void SetAudioStreamBufferSizeDefault(int size);" "\n"
"]]" "\n"
"" "\n"
"-- colors" "\n"
"local function new_color(r, g, b, a)" "\n"
"  local c = ffi.new(\"Color\")" "\n"
"  c.r = r" "\n"
"  c.g = g" "\n"
"  c.b = b" "\n"
"  c.a = a" "\n"
"  return c" "\n"
"end" "\n"
"" "\n"
"raylib.LIGHTGRAY = new_color(200, 200, 200, 255)" "\n"
"raylib.GRAY = new_color(130, 130, 130, 255)" "\n"
"raylib.DARKGRAY = new_color(80, 80, 80, 255)" "\n"
"raylib.YELLOW = new_color(253, 249, 0, 255)" "\n"
"raylib.GOLD = new_color(255, 203, 0, 255)" "\n"
"raylib.ORANGE = new_color(255, 161, 0, 255)" "\n"
"raylib.PINK = new_color(255, 109, 194, 255)" "\n"
"raylib.RED = new_color(230, 41, 55, 255)" "\n"
"raylib.MAROON = new_color(190, 33, 55, 255)" "\n"
"raylib.GREEN = new_color(0, 228, 48, 255)" "\n"
"raylib.LIME = new_color(0, 158, 47, 255)" "\n"
"raylib.DARKGREEN = new_color(0, 117, 44, 255)" "\n"
"raylib.SKYBLUE = new_color(102, 191, 255, 255)" "\n"
"raylib.BLUE = new_color(0, 121, 241, 255)" "\n"
"raylib.DARKBLUE = new_color(0, 82, 172, 255)" "\n"
"raylib.PURPLE = new_color(200, 122, 255, 255)" "\n"
"raylib.VIOLET = new_color(135, 60, 190, 255)" "\n"
"raylib.DARKPURPLE = new_color(112, 31, 126, 255)" "\n"
"raylib.BEIGE = new_color(211, 176, 131, 255)" "\n"
"raylib.BROWN = new_color(127, 106, 79, 255)" "\n"
"raylib.DARKBROWN = new_color(76, 63, 47, 255)" "\n"
"raylib.WHITE = new_color(255, 255, 255, 255)" "\n"
"raylib.BLACK = new_color(0, 0, 0, 255)" "\n"
"raylib.BLANK = new_color(0, 0, 0, 0)" "\n"
"raylib.MAGENTA = new_color(255, 0, 255, 255)" "\n"
"raylib.RAYWHITE = new_color(245, 245, 245, 255)" "\n"
"" "\n"
"raylib.__index = function (self, key)" "\n"
"  return raylib_so[key]" "\n"
"end" "\n"
"" "\n"
"raylib.__newindex = function ()" "\n"
"  error \"raylib table is readonly\"" "\n"
"end" "\n"
"" "\n"
"rl = setmetatable(raylib, raylib)" "\n"
"raylib = rl" "\n"
"local load = loadstring" "\n"
"" "\n"
"if raylua then" "\n"
"  -- Change the second loader to load files using raylua.loadfiles" "\n"
"  package.loaders[2] = function (name)" "\n"
"    for path in package.path:gmatch \"([^;]+);?\" do" "\n"
"      path = path:gsub(\"?\", name)" "\n"
"" "\n"
"      local status, content = raylua.loadfiles(path)" "\n"
"      if status then" "\n"
"        local f, err = load(content)" "\n"
"        assert(f, err)" "\n"
"" "\n"
"        return f" "\n"
"      end" "\n"
"    end" "\n"
"" "\n"
"    return nil" "\n"
"  end" "\n"
"end" "\n"
"" "\n"
"require \"main\"" "\n"
;